import Link from "next/link";
import { ArrowRight, CalendarDays, Landmark, ShieldCheck } from "lucide-react";

export default function Home() {
  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col px-5 py-6 sm:px-8">
      <header className="flex items-center justify-between"><span className="font-serif text-xl font-semibold text-stone-950">Clara</span><Link href="/login" className="rounded-full border border-stone-300 px-4 py-2 text-sm font-bold text-stone-800">Entrar</Link></header>
      <section className="grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-700">Finanzas sin ansiedad</p><h1 className="mt-4 max-w-3xl font-serif text-5xl font-semibold leading-[.98] tracking-tight text-stone-950 sm:text-7xl">Saber que puedes gastar tambien es tranquilidad.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-600">Un panel sencillo para registrar gastos, separar bolsillos y saber cuanto dinero pedir antes de quedar corta.</p><Link href="/login" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3.5 font-bold text-white shadow-lg shadow-emerald-900/15 hover:bg-emerald-700">Abrir mi panel <ArrowRight size={18} /></Link></div><div className="rounded-[2rem] bg-stone-900 p-6 text-white shadow-2xl shadow-stone-300"><p className="text-sm font-semibold text-stone-300">Vista previa</p><p className="mt-4 font-serif text-4xl font-semibold">$ 204.000</p><p className="mt-1 text-sm text-stone-400">Saldo en cuenta</p><div className="mt-7 rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">Antes de pedir dinero</p><p className="mt-2 text-lg font-semibold">Tus gastos y el dinero que falta, sin adivinar.</p></div></div></section>
      <section className="grid gap-4 border-t border-stone-200 py-7 sm:grid-cols-3"><div className="flex gap-3"><Landmark className="text-emerald-700" /><p className="text-sm text-stone-600"><b className="block text-stone-900">Bolsillos claros</b>Protege cada pago importante.</p></div><div className="flex gap-3"><CalendarDays className="text-emerald-700" /><p className="text-sm text-stone-600"><b className="block text-stone-900">Meses costosos</b>Anticipa ingles y acueducto.</p></div><div className="flex gap-3"><ShieldCheck className="text-emerald-700" /><p className="text-sm text-stone-600"><b className="block text-stone-900">Registro rapido</b>Menos de diez segundos por gasto.</p></div></section>
    </main>
  );
}
